Hack-PSU/frontend

website/index.html

changed it to:
http://hackp.ac/mlh-stickermule-hackathons
please blind accept thank

fixed stickermule logo link

---

.firebaserc
firebase.json
user-registration-app/src/app/views/login/login.component.html
user-registration-app/src/app/views/login/login.component.ts
user-registration-app/src/app/views/registration-form/registration-form.component.html
user-registration-app/src/app/views/registration-form/registration-form.component.ts

- Added firebase hosting config to user registration app 
- Added alert message on email if contains @psu.edu 
- Removed email field from registration form and added default email selection on submit

Integrating S2019 changes

---

.firebaserc
.travis.yml
README.md
firebase.json
scripts/deploy.sh
user-registration-app/src/app/views/rsvp/rsvp.component.html

* Fixed travis deployment
* Fixed silly comment issue on rsvp page
* Fixed the firebase deploy script

S2019: Rapix bug fixes and CI/CD updates

---

package.json
website/index.html

Updated package.json to include sass as production dependency for Travis

Removed repeated sponsors and other minor fixes (#68)

---

website/index.html

*very small change to prize description

Updates to main site and live site

---

user-registration-app/src/app/views/live-view/live-view.component.html
user-registration-app/src/app/views/registration-form/registration-form.component.html
user-registration-app/src/app/views/registration-form/registration-form.component.ts
user-registration-app/src/app/views/user-registration-view/user-registration-view.component.html
user-registration-app/src/app/views/user-registration-view/user-registration-view.component.ts
website/index.html

*Updating ec classes and registration form
*Updates to workshops and scheduling and business challenge on live site
*Update to route of login button on main site

Changes to live and main site

---

user-registration-app/src/app/views/live-view/live-view.component.html

* Changes to Adobe Workshop
* changes to workshop locations

Julia/ws changes2 (#96)

---

user-registration-app/src/app/app.component.html
user-registration-app/src/app/views/registration-form/registration-form.component.ts

Whitelisting data to keep after making new Registration object

Fixing registration data preservation across hackathons

---

user-registration-app/src/app/views/registration-form/registration-form.component.css
user-registration-app/src/app/views/registration-form/registration-form.component.html

added a quick change to the registration page for users to email us if they need help

registration page changes

---

website/index.html

Time variable fix

---

user-registration-app/src/app/views/user-registration-view/user-registration-view.component.html
website/business.html
website/index.html

Things to check on Review:
-Spelling and grammar
-all links work

Enabling Business Challenge Registration

---

user-registration-app/src/app/views/signup-view/signup-view.component.html
user-registration-app/src/app/views/signup-view/signup-view.component.ts

moving psu flag to sign up page

18ksharma patch 1

---

user-registration-app/src/app/views/user-registration-view/user-registration-view.component.ts

Things to check:
-go to local /profile route and make sure all ec classes are there
-make sure you can submit for new ec classes (you need to register locally first)

Enabling CMPSC 132

---

website/assets/images/border7-night.svg
website/index.html
website/scss/day-main.scss
website/scss/main.scss
website/scss/night-main.scss

All parts of the schedule view work well on my end. Things to check: screen size adjustments, code style.
One thing I noticed is that the section-separator is rendering borders on my screen at some varying screen sizes. I just spent about an hour trying to figure out why it's rendering to no avail. Maybe one of you could figure it out?

New schedule view

---

user-registration-app/src/app/models/registration.ts
user-registration-app/src/app/views/registration-form/registration-form.component.html
website/index.html

Apparently dashes break ngModels who would've thought

Ethnicity Fix

---

user-registration-app/src/app/views/registration-form/registration-form.component.css
user-registration-app/src/app/views/registration-form/registration-form.component.html
website/index.html

* Adding message from co-execs
* Changes to registration form to display message

Cancellation Message (#181)

---

website/index.html
website/json/particlesjs-config.json
website/scss/main.scss
website/scss/night-main.scss

Do you guys like the colors? I need to fix the particles to interact with the cursor in a future commit/PR, but I can't figure out why it do be like that for now.
Note: when testing, run an http server for the index. You can use the command python -m http.server while in the same folder as index.html to serve on localhost:8000. This prevents CORS issues when the js loads the json file.

Include Particle JS background on index; switch to night only styles

---

website/index.html

Changing sun to moon on firefox

---

user-registration-app/src/app/views/registration-form/registration-form.component.html

Let them register

---

user-registration-app/src/app/views/signup-view/signup-view.component.css
user-registration-app/src/app/views/signup-view/signup-view.component.html

Take a looksee. Pretty simple fix, but make sure you guys like it with the chrome developer tools on each mobile device.

fix signup buttons on livesite

---

package-lock.json
package.json
website/index.html
website/js/main.js
website/scss/main.scss

Jquery href broke. Bottom Text. I just replaced the jquery link in the index.html w/ google's jquery link and that fixed the FAQ buttons. I also fixed the issue where the mobile site was a few pixels to wide.

Fixed FAQ buttons and fixed mobile site sizing

---

user-registration-app/src/app/views/rsvp/rsvp.component.html

I just commented out the items to bring part of the rsvp component

commented out items to bring

---

website/scss/main.scss

Fixed planet positions and made sticker mule logo smaller on mobile.

Main Page Fixes For Prod Push

---

user-registration-app/src/app/views/schedule-view/schedule-view.component.css
user-registration-app/src/app/views/schedule-view/schedule-view.component.html
user-registration-app/src/app/views/schedule-view/schedule-view.component.ts

Added zoom and details buttons to schedule events

---

user-registration-app/src/app/views/live-view/live-view.component.css
user-registration-app/src/app/views/live-view/live-view.component.html
user-registration-app/src/environments/environment.ts

good css is for losers
i tried

Responsive buttons on Livesite

---

user-registration-app/src/environments/environment.prod.ts
user-registration-app/src/environments/environment.ts
website/index.html
website/scss/main.scss

- Updated env livesite times
- Updated "How long is the hackathon?" answer in FAQ
- Uncommented schedule (with mobile viewing improvements for text size)
Here's what the schedule looks like rn:

Schedule and Environment Livesite Times Update

---

user-registration-app/src/app/models/registration.ts
user-registration-app/src/app/services/HttpService/HttpService.ts
user-registration-app/src/app/views/user-registration-view/user-registration-view.component.css
user-registration-app/src/app/views/user-registration-view/user-registration-view.component.html
user-registration-app/src/app/views/user-registration-view/user-registration-view.component.ts

To test, create a new registration, then try to edit your address on profile page.

Sawyer/add address section -> dev

---

website/index.html
website/scss/main.scss

- Add CTF section and signup
- Also remove outdated tracks info

Add CTF Signup

---

user-registration-app/src/app/views/user-registration-view/user-registration-view.component.ts

The opposite of what we want to show in extra credit is shown because I forgot to undo a change lmao

Fix Filter Shown Classes

---

website/scss/main.scss

Remember kids, refactoring in WebStorm affects more than just the user registration app. BEEG planets on main site are now fixed.

Fixed a Boo Boo

---

package.json
website/index.html
website/scss/main.scss

Self explanatory, will revert the commit that disabled the links after the registration form is fixed

Update Dates on hackpsu.org and Disable Registration Links

---

website/index.html

- Forgot to change the registration status message (oops)

Prod Push Again

---

user-registration-app/src/app/views/registration-form/registration-form.component.html

Fixed Nav Links in Registration Form

---

package-lock.json
package.json
user-registration-app/package-lock.json
user-registration-app/src/index.html
website/business.html
website/index.html

Also remove Facebook Pixel code

Update Dependencies and Remove Facebook Pixel

---

user-registration-app/src/app/views/registration-form/registeredUserSchema.json
user-registration-app/src/app/views/registration-form/registration-form.component.html
user-registration-app/src/app/views/registration-form/registration-form.component.ts

A fast fix, MLH requires country as a field now

Make Country Required

---

user-registration-app/src/app/app.module.ts

Setting up the firebase storage module access.
Also making the linter a little happier

Enable Image Hosting Through Firebase

---

user-registration-app/src/app/views/signup-view/signup-view.component.html

Added a direct link to the Login page within the Signup page for those who already have an account. Added lines: 36-40

Added Log In link under Sign Up page

---

website/index.html

Travel FAQ

---

website/index.html

https://tinyurl.com/devisgoated

Signup bug and remove planets

---

website/index.html

times in FAQ question was wrong

Info fix for times

---

website/index.html

text changes for what is hackathon faq

text changes for what is hackathon faq

---

user-registration-app/src/app/views/user-registration-view/user-registration-view.component.html

MLH COC already updated with hyperlink, uncommented address box in user registration, updated discord link

restored address box for user registration

---

user-registration-app/src/app/app.component.html
user-registration-app/src/app/views/login/login.component.html
user-registration-app/src/app/views/rsvp/rsvp.component.html
user-registration-app/src/app/views/signup-view/signup-view.component.html

https://user-registration-na8vm8ehg-hackpsu.vercel.app/

minor changes to redirects and sign up / login choices
